=== dobregons/markup_language/xml/metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="geometry" type="xs:string"/>
<xs:element name="title" type="xs:string"/>
<xs:element name="description" type="xs:string"/>
<xs:element name="year" type="xs:int"/>
<xs:element name="month" type="xs:int"/>
<xs:element name="day" type="xs:int"/>
<xs:element name="postalCode" type="xs:string"/>
<xs:element name="city" type="xs:string"/>
<xs:element name="name" type="xs:string"/>
<xs:element name="surname" type="xs:string"/>

<xs:element name="origin">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="surname" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="location">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="postalCode" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="city" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="date">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="year" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="month" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="day" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="site">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="geometry" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="title" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="date" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="location" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="origin" minOccurs="1" maxOccurs="1"/>      
    </xs:sequence>
  </xs:complexType>
</xs:element>

  <xs:element name="metadata">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="site" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dobregons/markup_language/xml/Poligono4.xml
<?xml version="1.0" encoding="UTF-8"?>

<metadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="metadata.xsd">
	<site>
		<geometry>Poligono</geometry>
		<title>Coliseo el Salitre</title>
		<description>Este poligono describe el escenario más importante de la Unidad Deportiva El Salitre. En este escenario se efectúan principalmente compromisos deportivos ligados con los deportes bajo techo, como el baloncesto, voleibol, bádminton, tenis de mesa, karate, Taekwondoesgrima y Futsal entre otros.</description>
		<date>
			<year>2015</year>
			<month>06</month>
			<day>25</day>
		</date>		
		<location>
			<postalCode>111221</postalCode>
        	<city>Bogota</city>
		</location>
		<origin>
			<name>David</name>
			<surname>Obregon</surname>
		</origin>
	</site>
</metadata>

=== dobregons/markup_language/xml/Punto3.xml
<?xml version="1.0" encoding="UTF-8"?>

<metadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="metadata.xsd">
	<site>
		<geometry>Punto</geometry>
		<title>Universidad Libre</title>
		<description>Es la única universidad que se encuentra en la zona y es de las principales universidades en Bogotá. De igual manera se encuentra el colegio de la Universidad Libre dentro de ésta.</description>
		<date>
			<year>2015</year>
			<month>06</month>
			<day>25</day>
		</date>		
		<location>
			<postalCode>111221</postalCode>
        	<city>Bogota</city>
		</location>
		<origin>
			<name>David</name>
			<surname>Obregon</surname>
		</origin>
	</site>
</metadata>

=== dobregons/markup_language/xml/Poligono3.xml
<?xml version="1.0" encoding="UTF-8"?>

<metadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="metadata.xsd">
	<site>
		<geometry>Poligono</geometry>
		<title>Jardin Botánico</title>
		<description>Este poligono representa el jardín botánico más grande de Colombia. Es un lugar de investigación, educación y ocio de la capital colombiana.</description>
		<date>
			<year>2015</year>
			<month>06</month>
			<day>25</day>
		</date>		
		<location>
			<postalCode>111221</postalCode>
        	<city>Bogota</city>
		</location>
		<origin>
			<name>David</name>
			<surname>Obregon</surname>
		</origin>
	</site>
</metadata>

=== dobregons/markup_language/xml/Linea1.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="metadata.xsd">
	<site>
		<geometry>Linea</geometry>
		<title>Universidad Libre - Salitre Mágico</title>
		<description>Esta linea describe la ruta entre la Universidad Libre ubicada en Normandia, hacia el parque Salitre Mágico localizado en de Barrios Unidos. Es una de las rutas mas usadas para llegar al parque desde la avenida Rojas.</description>
		<date>
			<year>2015</year>
			<month>06</month>
			<day>25</day>
		</date>		
		<location>
			<postalCode>111221</postalCode>
        	<city>Bogota</city>
		</location>
		<origin>
			<name>David</name>
			<surname>Obregon</surname>
		</origin>
	</site>
</metadata>

=== dobregons/markup_language/xml/Poligono2.xml
<?xml version="1.0" encoding="UTF-8"?>

<metadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="metadata.xsd">
	<site>
		<geometry>Poligono</geometry>
		<title>Salitre Mágico</title>
		<description>Este poligono describe el principal parque de atracciones en Bogotá. Queda ubicado en la localidad de barrios unidos y tiene atracciones para todo tipo de publico.</description>
		<date>
			<year>2015</year>
			<month>06</month>
			<day>25</day>
		</date>		
		<location>
			<postalCode>111221</postalCode>
        	<city>Bogota</city>
		</location>
		<origin>
			<name>David</name>
			<surname>Obregon</surname>
		</origin>
	</site>
</metadata>

=== dobregons/markup_language/xml/Linea2.xml
<?xml version="1.0" encoding="UTF-8"?>

<metadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="metadata.xsd">
	<site>
		<geometry>Linea</geometry>
		<title>Palacio de los Deportes - Coliseo el Salitre</title>
		<description>Esta linea describe la ruta entre el palacio de los deportes y el coliseo el salitre. Usualmente son los dos sitios principales para practicar deporte y organizar eventos deportivos en la ciudad de Bogot√°. Ambos sitios son muy visitados por turistas.</description>
		<date>
			<year>2015</year>
			<month>06</month>
			<day>25</day>
		</date>		
		<location>
			<postalCode>111221</postalCode>
        	<city>Bogota</city>
		</location>
		<origin>
			<name>David</name>
			<surname>Obregon</surname>
		</origin>
	</site>
</metadata>

=== dobregons/markup_language/xml/Punto4.xml
<?xml version="1.0" encoding="UTF-8"?>

<metadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="metadata.xsd">
	<site>
		<geometry>Punto</geometry>
		<title>Palacio de los deportes</title>
		<description>Es un coliseo cubierto con modernas instalaciones que puede albergar importantes torneos deportivos profesionales como de aficionados. Igualmente es ideal para eventos culturales, empresariales, teatrales y musicales.</description>
		<date>
			<year>2015</year>
			<month>06</month>
			<day>25</day>
		</date>		
		<location>
			<postalCode>111221</postalCode>
        	<city>Bogota</city>
		</location>
		<origin>
			<name>David</name>
			<surname>Obregon</surname>
		</origin>
	</site>
</metadata>

=== dobregons/markup_language/xml/Punto2.xml
<?xml version="1.0" encoding="UTF-8"?>

<metadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="metadata.xsd">
	<site>
		<geometry>Punto</geometry>
		<title>Biblioteca Virgilio Barco</title>
		<description>La biblioteca Virgilio Barco se caracteriza por ser una de las mas grandez y completas en Bogotá y en el país. Visitada diariamente por cientos de personas.</description>
		<date>
			<year>2015</year>
			<month>06</month>
			<day>25</day>
		</date>		
		<location>
			<postalCode>111221</postalCode>
        	<city>Bogota</city>
		</location>
		<origin>
			<name>David</name>
			<surname>Obregon</surname>
		</origin>
	</site>
</metadata>
