=== dobregons/markup_language/xml/metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="geometry" type="xs:string"/>
<xs:element name="title" type="xs:string"/>
<xs:element name="description" type="xs:string"/>
<xs:element name="year" type="xs:int"/>
<xs:element name="month" type="xs:int"/>
<xs:element name="day" type="xs:int"/>
<xs:element name="postalCode" type="xs:string"/>
<xs:element name="city" type="xs:string"/>
<xs:element name="name" type="xs:string"/>
<xs:element name="surname" type="xs:string"/>

<xs:element name="origin">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="surname" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="location">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="postalCode" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="city" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="date">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="year" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="month" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="day" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="site">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="geometry" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="title" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="date" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="location" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="origin" minOccurs="1" maxOccurs="1"/>      
    </xs:sequence>
  </xs:complexType>
</xs:element>

  <xs:element name="metadata">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="site" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dobregons/markup_language/xml/Poligono1.xml
<?xml version="1.0" encoding="UTF-8"?>

<metadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="metadata.xsd">
	<site>
		<geometry>Poligono</geometry>
		<title>Parque Simon Bolivar</title>
		<description>Representa el parque m치s grande de Bogot치, el cual cuenta con una gran cantidad de zonas verdes y lo convierte en uno de los sitios turisticos m치s importantes de Bogot치.</description>
		<date>
			<year>2015</year>
			<month>06</month>
			<day>25</day>
		</date>		
		<location>
			<postalCode>111221</postalCode>
        	<city>Bogota</city>
		</location>
		<origin>
			<name>David</name>
			<surname>Obregon</surname>
		</origin>
	</site>
</metadata>

=== dobregons/markup_language/xml/Punto1.xml
<?xml version="1.0" encoding="UTF-8"?>

<metadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="metadata.xsd">
	<site>
		<geometry>Punto</geometry>
		<title>Montaña Rusa Salitre Mágico</title>
		<description>La montaña rusa de salitre mágico es una de las principales atracciones de este establecimiento, muy visitada por turistas de otras partes del país.</description>
		<date>
			<year>2015</year>
			<month>06</month>
			<day>25</day>
		</date>		
		<location>
			<postalCode>111211</postalCode>
        	<city>Bogota</city>
		</location>
		<origin>
			<name>David</name>
			<surname>Obregon</surname>
		</origin>
	</site>
</metadata>
